apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: nget-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: nget-app
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
